export const ActionTypes = {
  GET_ORDERS: 'GET_ORDERS',
  GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
  GET_ORDERS_FAILURE: 'GET_ORDERS_FAILURE',
  GET_POSITIONS_ORDER: 'GET_POSITIONS_ORDER',
  GET_POSITIONS_ORDER_SUCCESS: 'GET_POSITIONS_ORDER_SUCCESS',
  GET_POSITIONS_ORDER_FAILURE: 'GET_POSITIONS_ORDER_FAILURE'
}
